In [1]:
import pandas as pd
ad=pd.read_csv("Advertising.csv")
df=ad.copy()
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [2]:
#get predictors
X=df.drop("sales",axis=1)

In [3]:
X.head()

Unnamed: 0     TV  radio  newspaper
0           1  230.1   37.8       69.2
1           2   44.5   39.3       45.1
2           3   17.2   45.9       69.3
3           4  151.5   41.3       58.5
4           5  180.8   10.8       58.4

In [5]:
y=df["sales"]
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [7]:
#split the set
from sklearn.model_selection import train_test_split,cross_val_score,cross_val_predict

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [10]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [13]:
lm=sm.OLS(y_train,X_train)

In [14]:
model=lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.985
Model:                            OLS   Adj. R-squared (uncentered):              0.984
Method:                 Least Squares   F-statistic:                              2482.
Date:                Wed, 26 Jan 2022   Prob (F-statistic):                   4.66e-140
Time:                        23:26:50   Log-Likelihood:                         -326.71
No. Observations:                 160   AIC:                                      661.4
Df Residuals:                     156   BIC:                                      673.7
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Unnamed: 0     0.0094      0.002      4.543      0.000       0.005       0.014
TV             0.0500      0.002     32.472      0.000       0.047       0.053
radio          0.2091      0.010     19.978      0.000       0.188       0.230
newspaper      0.0205      0.008      2.731      0.007       0.006       0.035
==============================================================================
Omnibus:                       25.600   Durbin-Watson:                   1.911
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.489
Skew:                          -0.757   Prob(JB):                     4.87e-11
Kurtosis:                       5.198   Cond. No.                         15.5
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
from sklearn.linear_model import LinearRegression

In [19]:
lm=LinearRegression()
model=lm.fit(X_train,y_train)
model

LinearRegression()

In [20]:
model.coef_

array([0.00064359, 0.04471835, 0.18925118, 0.00304577])

In [28]:
new_input=[[1],[30],[10],[20]]
new_input=pd.DataFrame(new_input).T
new_input

0   1   2   3
0  1  30  10  20

In [29]:
model.predict(new_input)

array([6.20214839])

In [31]:
import numpy as np
from sklearn.metrics import mean_squared_error 
rmse=np.sqrt(mean_squared_error(y_train,model.predict(X_train)))
rmse

1.6442982086509947

In [32]:
rmse=np.sqrt(mean_squared_error(y_test,model.predict(X_test)))
rmse

1.7885761008659655

In [37]:
cross_val_score(model,X,y,cv=100,scoring="r2")

array([ 9.05299307e-01,  7.46631085e-01, -9.67935456e-01, -1.17826647e-01,
        6.89831803e-01,  9.36926481e-01, -2.16417681e+01,  5.03174754e-01,
        9.79051157e-01,  6.40879142e-01,  6.27198489e-01,  9.55096576e-01,
       -5.21912483e+00, -2.71298092e+00,  9.40199406e-01,  9.92313844e-01,
        7.94833576e-01, -3.16385001e+00,  9.11838740e-01,  9.82926909e-01,
        3.04242239e-01,  9.25023943e-01,  9.86735984e-01,  9.34943714e-01,
        6.48676786e-01, -1.29722265e+01, -4.69416274e+00,  1.22970059e-02,
        6.67746958e-01,  7.37836725e-01,  9.43261231e-01, -2.88284801e-01,
        9.15541595e-01,  7.24308189e-01,  7.50106042e-01,  8.03701946e-01,
       -5.71887907e-01,  6.72723423e-01,  7.65153516e-01,  8.88479351e-02,
       -4.68205426e+01,  2.65315841e-01,  9.59175818e-01,  9.58241867e-01,
        7.86075550e-01, -3.03362089e-01,  7.18560294e-01,  9.04372096e-01,
        8.68244264e-01,  9.45320247e-01,  9.28542551e-01, -1.69847296e+03,
       -6.65578303e-01, -

In [39]:
cross_val_score(model,X,y,cv=10,scoring="r2").mean()

0.8824997330280173

In [40]:
cross_val_score(model,X,y,cv=10,scoring="r2")

array([0.87074153, 0.84929412, 0.92990198, 0.88982108, 0.93148951,
       0.93118906, 0.75841122, 0.91195192, 0.83320962, 0.91898728])